# Generated by Django 4.1.3 on 2022-11-18 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_complex_cell_height_and_more'),
        ('users', '0002_contact_complex_alter_contact_contact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='380730318940', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='complex',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complex_contact', to='content.complex'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
