# Generated by Django 4.1.3 on 2022-11-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contact_phone_alter_contact_complex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_developer',
            field=models.BooleanField(default=False, verbose_name='Застройщик'),
        ),
    ]
