# Generated by Django 4.1.3 on 2022-11-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_is_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='forward_to_agent',
            field=models.BooleanField(default=False, verbose_name='Переключать на агента'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_blacklisted',
            field=models.BooleanField(default=False, verbose_name='В черном списке'),
        ),
    ]
