# Generated by Django 4.1.3 on 2022-11-23 22:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0689875898', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='auto_continue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
