# Generated by Django 4.1.3 on 2022-11-24 23:13

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_favourite_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notary',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0965698989', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 1, 13, 9, 764624), null=True),
        ),
    ]
