# Generated by Django 4.1.3 on 2022-11-25 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_subscription_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 10, 37, 54, 508878), null=True),
        ),
    ]
