# Generated by Django 4.1.3 on 2022-11-25 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_subscription_expired_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='message',
            name='is_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 14, 20, 48, 235483), null=True),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.message')),
            ],
        ),
    ]
