# Generated by Django 4.1.3 on 2022-11-27 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_message_recipient_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 19, 30, 53, 278475), null=True),
        ),
    ]
