# Generated by Django 4.1.3 on 2022-11-29 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_filter_apartment_type_alter_filter_area_high_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyFunctionalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('map_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('map_long', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='filter',
            name='apartment_type',
            field=models.CharField(blank=True, choices=[('Новострои', 'Новострои'), ('Вторичный рынок', 'Вторичный рынок'), ('Коттеджи', 'Коттеджи')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 23, 25, 46, 943517), null=True),
        ),
    ]
