# Generated by Django 4.1.3 on 2022-11-29 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_manyfunctionalcenter_alter_filter_apartment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 0, 1, 55, 758783), null=True),
        ),
    ]
