# Generated by Django 4.1.3 on 2022-11-30 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_subscription_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 10, 8, 19, 212182), null=True),
        ),
    ]
