# Generated by Django 4.1.3 on 2022-12-01 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_subscription_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 7, 39, 35, 571418, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
