services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: make startapp
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
  celery:
    restart: always
    build:
      context: .
    command: celery -A APISwipe worker --loglevel=info
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A APISwipe beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./.env.prod
    depends_on:
      - celery
volumes:
  postgres_data:
  static_volume:
  media_volume: