# Generated by Django 4.1.3 on 2022-11-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='cell_height',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='complex',
            name='distance_to_sea',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complex',
            name='electricity',
            field=models.CharField(choices=[('connect', 'Подключено'), ('disconnect', 'Отключено')], default='connect', max_length=10),
        ),
        migrations.AlterField(
            model_name='complex',
            name='formalization',
            field=models.CharField(choices=[('justice', 'Юстиция'), ('proxy', 'Доверенность')], default='justice', max_length=20),
        ),
        migrations.AlterField(
            model_name='complex',
            name='heating',
            field=models.CharField(choices=[('central', 'Центральное'), ('auto', 'Автономное')], default='central', max_length=10),
        ),
        migrations.AlterField(
            model_name='complex',
            name='invoice',
            field=models.CharField(choices=[('invoice', 'Платежи'), ('transaction', 'Актиный платеж')], default='invoice', max_length=30),
        ),
        migrations.AlterField(
            model_name='complex',
            name='payment_form',
            field=models.CharField(choices=[('onlycash', 'Только наличные'), ('capital', 'Мат. капитал'), ('mortgage', 'Ипотека'), ('no matter', 'Неважно')], default='onlycash', max_length=20),
        ),
        migrations.AlterField(
            model_name='complex',
            name='payments_part',
            field=models.CharField(choices=[('all', 'Полная'), ('part', 'Неполная')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='complex',
            name='purpose',
            field=models.CharField(choices=[('flat', 'Квартира'), ('commercial', 'Для коммерции'), ('living', 'Жилое помещение')], default='flat', max_length=30),
        ),
        migrations.AlterField(
            model_name='complex',
            name='sewerage',
            field=models.CharField(choices=[('central', 'Центральное'), ('auto', 'Автономное')], default='central', max_length=10),
        ),
        migrations.AlterField(
            model_name='complex',
            name='water_cupply',
            field=models.CharField(choices=[('central', 'Центральное'), ('auto', 'Автономное')], default='central', max_length=10),
        ),
    ]
