# Generated by Django 4.1.3 on 2022-11-18 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_complexbenefits_complex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexbenefits',
            name='complex',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complex_benefits', to='content.complex'),
        ),
    ]
