# Generated by Django 4.1.3 on 2022-11-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_apartment_owner_alter_complex_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='area_from',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complex',
            name='area_to',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complex',
            name='min_price',
            field=models.PositiveIntegerField(default=200000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complex',
            name='price_per_m2',
            field=models.PositiveIntegerField(default=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complexdocument',
            name='file_format',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='complex',
            name='cell_height',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='complex',
            name='map_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='complex',
            name='map_long',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='complexdocument',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_documents', to='content.complex'),
        ),
        migrations.AlterField(
            model_name='complexdocument',
            name='file',
            field=models.FileField(upload_to='complexes/documents/'),
        ),
        migrations.AlterField(
            model_name='compleximage',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_images', to='content.complex'),
        ),
        migrations.AlterField(
            model_name='compleximage',
            name='image',
            field=models.ImageField(upload_to='complexes/images/'),
        ),
    ]
