# Generated by Django 4.1.3 on 2022-11-21 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_complex_area_from_complex_area_to_complex_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexdocument',
            name='file_format',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='complexnews',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_news', to='content.complex'),
        ),
    ]
