# Generated by Django 4.1.3 on 2022-11-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_complexdocument_file_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_images', to='content.apartment'),
        ),
    ]
