# Generated by Django 4.1.3 on 2022-11-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_apartment_is_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='communication_type',
            field=models.CharField(choices=[('Звонок + сообщение', 'Звонок + сообщение'), ('Только звонки', 'Только звонки'), ('Сообщение', 'Сообщение')], max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='heating',
            field=models.CharField(choices=[('Газовое', 'Газовое'), ('Електро', 'Електро')], max_length=20),
        ),
    ]
