# Generated by Django 4.1.3 on 2022-11-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_apartment_communication_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='schema',
            field=models.ImageField(blank=True, null=True, upload_to='complexes/None/apartment-<django.db.models.fields.PositiveIntegerField>/schema/'),
        ),
    ]
