# Generated by Django 4.1.3 on 2022-11-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_apartment_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='kitchenArea',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
