# Generated by Django 4.1.3 on 2022-11-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_apartment_area_alter_apartment_kitchenarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='floor_count',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
