# Generated by Django 4.1.3 on 2022-11-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_section_floor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
