# Generated by Django 4.1.3 on 2022-11-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_apartment_is_moderated_apartment_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='corpus',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rises',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='section',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('complex', 'section', 'floor', 'rises', 'number')},
        ),
    ]
