# Generated by Django 4.1.3 on 2022-11-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_apartment_corpus_alter_apartment_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='condition',
            field=models.CharField(choices=[('Требуется ремонт', 'Требуется ремонт'), ('Жилое', 'Жилое'), ('Голые стена', 'Голые стены')], max_length=30),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='foundation',
            field=models.CharField(choices=[('Фз 2014', 'Фз 2014'), ('Случайная', 'Случайная')], max_length=200),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='kitchenArea',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='payment_options',
            field=models.CharField(choices=[('Только наличные', 'Только наличные'), ('Мат. капитал', 'Мат. капитал'), ('Ипотека', 'Ипотека'), ('Неважно', 'Неважно')], max_length=30),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='plan',
            field=models.CharField(choices=[('Студия, санузел', 'Студия, санузел'), ('Обынчая', 'Обычная')], max_length=30),
        ),
    ]
