# Generated by Django 4.1.3 on 2022-11-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_apartment_area_alter_apartment_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='add_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='add_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='color',
            field=models.CharField(blank=True, choices=[('#d13fcf', 'Розовый'), ('#93cf9b', 'Зеленый')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_big',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_turbo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='text',
            field=models.CharField(blank=True, choices=[('Подарок при покупке', 'Подарок при покупке'), ('Возможет торг', 'Возможен торг'), ('Квартира у моря', 'Квартира у моря'), ('В спальном районе', 'В спальном районе'), ('Вам повезло с ценой!', 'Вам повезло с ценой!'), ('Для большой семьи', 'Для большой семьи'), ('Семейное гнездышко', 'Семейное гнездышко'), ('Отедльная парковка', 'Отдельная парковка')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='purpose',
            field=models.CharField(choices=[('Апартаменты', 'Апартаменты'), ('Коттедж', 'Коттедж')], max_length=20),
        ),
    ]
