# Generated by Django 4.1.3 on 2022-11-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_advertisement_add_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_corpus', to='content.complex'),
        ),
    ]
