# Generated by Django 4.1.3 on 2022-11-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_apartment_options_apartment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
