# Generated by Django 4.1.3 on 2022-11-25 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0025_alter_apartment_is_viewed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='is_viewed',
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_viewed',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
