# Generated by Django 4.1.3 on 2022-11-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_remove_apartment_is_viewed_apartment_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentimage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
