# Generated by Django 4.1.3 on 2022-11-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_apartmentimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='expired_end',
            field=models.DateField(null=True),
        ),
    ]
