# Generated by Django 4.1.3 on 2022-12-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_advertisement_expired_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='map_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='map_long',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='condition',
            field=models.CharField(choices=[('Требуется ремонт', 'Требуется ремонт'), ('Жилое', 'Жилое'), ('Голые стены', 'Голые стены')], max_length=30),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='plan',
            field=models.CharField(choices=[('Студия, санузел', 'Студия, санузел'), ('Обычная', 'Обычная')], max_length=30),
        ),
    ]
